import Head from "next/head";
import { useRef, useState } from "react";
import NavBar from "../components/navBar";
import styles from "../styles/Home.module.css";

export default function Feedback() {

  const outputDivRef = useRef(null);
  const [userDetails, setUserDetails] = useState({});

  const handleSubmit = (e) => {
    // Stop the form from submitting and refreshing the page.
    e.preventDefault();

    console.log(e.target.name.value, e.target.email.value);
    outputDivRef.current.style.display = "block";

    setUserDetails({
        name: e.target.name.value,
        email: e.target.email.value
    });

  };

  return (
    <div className="flex items-center justify-center h-screen w-screen">
      <Head>
        <title>Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div>
        <form className="border-2 p-4 drop-shadow-md w-[50vh] flex flex-col rounded" onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Name"
            name="name"
            className="borderStyle"
            required
          />
          <input
            type="email"
            placeholder="Email"
            name="email"
            className="borderStyle"
            required
          />
          <button
            type="submit"
            className="bg-blue-400 w-2/4 p-2 font-bold text-white self-center rounded"
          >
            {" "}
            Submit{" "}
          </button>
        </form>

        <div className="hidden drop-shadow-md border-2 mt-4 rounded p-4 text-center" ref={outputDivRef}>
          <h3 className="font-semibold">Output Comes here</h3>
          <p>Name: {userDetails.name}</p>
          <p>Email: {userDetails.email}</p>
        </div>
      </div>
    </div>
  );
}
