import Head from 'next/head'
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Home() {

  const [counter, setCounter] = useState(10);
  const router = useRouter();

  useEffect(() => {
    const timer = setInterval(() => {
      setCounter((counter) => counter - 1);
    }, 1000);

    // cleanup --> component unmount
    return () => {
      clearTimeout(timer);
    }
  }, [])

  useEffect(() => {

    if(counter === 0) {
      router.push('/feedback');
    }

  }, [counter])

  return (
    <div className='h-screen w-screen flex items-center justify-center'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='drop-shadow-md border-2 p-4 w-[50vw] rounded'>
        <p className='text-center font-semibold'>
        Count Down
          </p> 
        <p className='text-center text-xl mt-2'>
          {counter}
        </p>
      </div>
    </div>
  )
}
